spring.application.name=WebStore

server.port=8080
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ukmthbjjoszeniuofldq
spring.datasource.password=GXHZzYX4IbPHdNC1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.hbm2ddl.generate_statistics=true

#logging.level.org.hibernate=DEBUG

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html

supabase.url=https://ukmthbjjoszeniuofldq.supabase.co
supabase.api-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrbXRoYmpqb3N6ZW5pdW9mbGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTgwMDQsImV4cCI6MjA2MjAzNDAwNH0.a6lGwEjbmCChIPs5mlfeS8NI3ij0dIznOs0TqZp_X6k
supabase.bucket-images=product-images
supabase.bucket-user-profile-images=user-images
supabase.bucket-category-images=category-images